# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ggispert <ggispert@student.42barcelona.    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/23 18:43:48 by ggispert          #+#    #+#              #
#    Updated: 2023/02/21 17:30:13 by ggispert         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =	libft.a
SRCS = 	ft_isalpha.c ft_isupper.c ft_islower.c ft_isdigit.c ft_isalnum.c  ft_isascii.c ft_isprint.c\
		ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c\
		ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c\
		ft_strnstr.c  ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c 
OBJS =	$(SRCS:.c=.o)
CFLAGS = -Wall -Werror -Wextra
HEADER = libft.h

%.o : %.c $(HEADER)
	$(CC) $(CFLAGS) $< -c

all: 
	$(MAKE) $(NAME)

$(NAME): $(OBJS)
	ar -rcs $(NAME) $(OBJS)

clean:
	rm -f *.o

fclean:
	$(MAKE) clean
	rm -f $(NAME)

re:	
	$(MAKE) fclean $(NAME)

.PHONY : all bonus clean fclean re
